name: Build and Publish Release

on:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            arch: x86_64
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            arch: aarch64
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            arch: i686
            os: ubuntu-latest
          - target: arm-unknown-linux-gnueabi
            arch: arm
            os: ubuntu-latest
          - target: arm-unknown-linux-gnueabihf
            arch: armhf
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            arch: armv7
            os: ubuntu-latest

          - target: x86_64-unknown-linux-musl
            arch: x86_64.musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            arch: aarch64.musl
            os: ubuntu-latest
          - target: i686-unknown-linux-musl
            arch: i686.musl
            os: ubuntu-latest
          - target: arm-unknown-linux-musleabi
            arch: arm.musl
            os: ubuntu-latest
          - target: arm-unknown-linux-musleabihf
            arch: armhf.musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            arch: armv7.musl
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: lpm
          target: ${{ matrix.target }}
          archive: "$bin-${{ matrix.arch }}"
          token: ${{ secrets.GITHUB_TOKEN }}
